spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gosvea.cf0q6si6co44.us-east-1.rds.amazonaws.com:3306/gosvea?useSSL=false&allowMultiQueries=true
    username: admin
    password: Gosvea2024!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: gosvea@usjus.org
    password: jzbh dfpb wtdh rusw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  data:
    redis:
      host: 54.175.129.180
      port: 6379
      password: Gosvea2024@
      timeout: 6000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.gosvea.mapper

server:
  address: 0.0.0.0

